export const CDNImageLink= "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/"
export const CDNMenuIm ="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/"
export const CDNLogoIm="https://image.similarpng.com/very-thumbnail/2021/09/Good-food-logo-design-on-transparent-background-PNG.png"
export const VEGIm="https://upload.wikimedia.org/wikipedia/commons/d/d4/Vegan_friendly_icon.png"
export const NONVEGIm="https://www.pngkey.com/png/full/270-2702996_non-veg-portable-network-graphics.png"
export const StarIm="https://icons.iconarchive.com/icons/goodstuff-no-nonsense/free-space/512/star-icon.png"
export const CDNRestoIm1="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=19.07480&lng=72.88560&restaurantId="
export const CDNRestoIm2="&catalog_qa=undefined&submitAction=ENTER"
export const PercentageIm ="https://www.iconpacks.net/icons/2/free-percent-icon-2037-thumb.png"
export const CDNCarouselIm="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/"
export const CDNSearchImg="https://cdn-icons-png.flaticon.com/128/54/54481.png"
export const CDNContactIMg="https://cdn-icons-png.flaticon.com/128/3249/3249904.png"
export const CDNEmptycart="https://cdn-icons-png.flaticon.com/128/11329/11329060.png"
export const CDNFullCart="https://cdn-icons-png.flaticon.com/128/3082/3082011.png"
export const CDNprofile="https://cdn-icons-png.flaticon.com/128/1177/1177568.png"
export const CDNaboutus="https://cdn-icons-png.flaticon.com/128/12355/12355338.png"
export const CDNSignUp="https://cdn-icons-png.flaticon.com/128/5836/5836185.png"
export const CDNsignIn="https://cdn-icons-png.flaticon.com/128/6358/6358961.png"
export const CarouselLink1 ="https://www.swiggy.com/dapi/restaurants/list/v5?lat=18.61610&lng=73.72860&collection="
export const CarouselLink2 ="&sortBy=&filters=&type=rcv2&offset=0&page_type=null"
