export const CDNImageLink= "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/"
export const CDNMenuIm ="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/"
export const CDNLogoIm="https://img.freepik.com/free-vector/food-shopping-logo-template-design_460848-10299.jpg"
export const VEGIm="https://upload.wikimedia.org/wikipedia/commons/d/d4/Vegan_friendly_icon.png"
export const NONVEGIm="https://www.pngkey.com/png/full/270-2702996_non-veg-portable-network-graphics.png"
export const StarIm="https://icons.iconarchive.com/icons/goodstuff-no-nonsense/free-space/512/star-icon.png"
export const CDNRestoIm1="https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=19.07480&lng=72.88560&restaurantId="
export const CDNRestoIm2="&catalog_qa=undefined&submitAction=ENTER"
export const PercentageIm ="https://www.iconpacks.net/icons/2/free-percent-icon-2037-thumb.png"
// export const CDNLogoIm="https://www.google.com/imgres?q=food%20logo%20png%20transparent&imgurl=https%3A%2F%2Fimg.lovepik.com%2Felement%2F45006%2F2391.png_860.png&imgrefurl=https%3A%2F%2Flovepik.com%2Fimages%2Fpng-food-logo.html&docid=6VBy_w7XEeqFkM&tbnid=9AS1HcZZ2xNdUM&vet=12ahUKEwiWyNndh8SGAxVi3TgGHWfEA28QM3oECGYQAA..i&w=860&h=1108&hcb=2&ved=2ahUKEwiWyNndh8SGAxVi3TgGHWfEA28QM3oECGYQAA"